pipeline{
  agent any
  stages{
    stage('Build'){
      steps{
        def scriptPath = '/var/lib/jenkins/jenkins-docker-ecr-push/docker_ci_build_ecr/docker_python/docker_ecr_push.sh'
        sh "chmod +x ${scriptPath}"
        sh "./${scriptPath}"
      }
    }
  }
  post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
