pipeline{
  agent any
  stages{
    stage('Build'){
      steps{
        echo 'hello everyone'
       
      }
    }
  }
  post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
