pipeline{
  agent any
  stages{
    stage('Build'){
      steps{
        echo 'hello everyone'
        sh "chmod +x /var/lib/jenkins/workspace/jenkins-docker-ecr-push/docker_ci_build_ecr/docker_python/docker_ecr_push.sh"
        sh "./var/lib/jenkins/workspace/jenkins-docker-ecr-push/docker_ci_build_ecr/docker_python/docker_ecr_push.sh"
       
      }
    }
  }
  post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
